# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on:
  push:

permissions:
  issues: write
  checks: write
  contents: write
  pull-requests: write

env:
  TYPE: ${{ endsWith(github.ref_name, 'beta') && 'beta' || 'release' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "⬇️ Checkout"
        uses: actions/checkout@v6

      - name: "🔃 Use Latest Node.js"
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: "🧵 Install semantic release"
        run: npm i --location=global semantic-release conventional-changelog-conventionalcommits @semantic-release/github @semantic-release/changelog @semantic-release/exec semantic-release-export-data semantic-release-discord-notifier

      - name: "🔢 Determine version"
        run: npx semantic-release --dry-run
        id: get-next-version
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: "ℹ️ Needs Release?"
        run: echo "Needs release published? ${{ steps.get-next-version.outputs.new-release-published == 'true' }}"

      - name: "Package and Publish"
        if: ${{ steps.get-next-version.outputs.new-release-published == 'true'  }}
        run: cd src && zip -r ../Pacify-Mobs-${{ steps.get-next-version.outputs.new-release-version }}.zip *

      - name: "🏗️ Build & Release to GitHub"
        if: ${{ steps.get-next-version.outputs.new-release-published == 'true'  }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: npx semantic-release

      - uses: Kir-Antipov/mc-publish@v3.3
        name: "🚀 Publish on modrinth"
        if: ${{ steps.get-next-version.outputs.new-release-published == 'true' }}
        with:
          version-type: ${{ env.TYPE }}
          name: Pacify Mobs v${{ steps.get-next-version.outputs.new-release-version }}
          version: ${{ steps.get-next-version.outputs.new-release-version }}
          modrinth-id: ${{ vars.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          changelog-file: CHANGELOG.*
          files: Pacify-Mobs-${{ steps.get-next-version.outputs.new-release-version }}.zip
          loaders: |
            datapack
          game-versions: |
            >=1.21.9
          game-version-filter: releases
